import type { APIRoute } from 'astro';
import { routeIncomingBOM } from '../../data/sales-routing';
import { supabase, saveBOMSubmission } from '../../lib/supabase';

// 是否启用云端存储（根据环境变量判断）
const ENABLE_CLOUD_STORAGE = !!import.meta.env.SUPABASE_URL && !!import.meta.env.SUPABASE_ANON_KEY;

// 系统匿名用户ID（用于自动发布BOM优化文章）
const SYSTEM_USER_ID = 'system-bom-user-id-00000000';

// 解析BOM内容，提取型号和数量
function parseBOMContent(bomText: string): { parts: Array<{ partNumber: string; quantity: string }>; totalItems: number } {
  const parts: Array<{ partNumber: string; quantity: string }> = [];
  const lines = bomText.split('\n').filter(line => line.trim());
  
  for (const line of lines) {
    // 匹配常见的BOM格式：数量 型号 描述
    const match = line.match(/^\s*(\d+)\s+([A-Za-z0-9._-]+)\s*.*/);
    if (match) {
      parts.push({
        partNumber: match[2],
        quantity: match[1]
      });
    } else {
      // 尝试匹配只有型号的行
      const partMatch = line.match(/^[A-Za-z0-9._-]{5,}/);
      if (partMatch) {
        parts.push({
          partNumber: partMatch[0],
          quantity: '1'
        });
      }
    }
  }
  
  return { parts, totalItems: parts.length };
}

// 自动发布BOM优化板块文章（匿名）
async function autoPublishBOMOptimization(bomText: string): Promise<boolean> {
  try {
    if (!ENABLE_CLOUD_STORAGE) {
      console.log('[BOM Auto Publish] ⚠️ Cloud storage disabled, skipping auto publish');
      return false;
    }
    
    const parsed = parseBOMContent(bomText);
    
    if (parsed.totalItems === 0) {
      console.log('[BOM Auto Publish] ⚠️ No parts found in BOM, skipping auto publish');
      return false;
    }
    
    // 生成匿名文章内容
    const sampleParts = parsed.parts.slice(0, 5);
    const moreCount = parsed.totalItems - sampleParts.length;
    
    const titleCn = `BOM优化需求 - ${parsed.totalItems}个元器件寻源`;
    const contentCn = `## 匿名BOM优化需求

用户提交了一份包含 **${parsed.totalItems}** 个元器件的BOM清单，寻求优化方案。

### 需求清单（部分）

| 型号 | 数量 |
|------|------|
${sampleParts.map(p => `| ${p.partNumber} | ${p.quantity} |`).join('\n')}
${moreCount > 0 ? `| ... | 还有 ${moreCount} 个型号 |` : ''}

### 优化方向

- 📊 国产替代方案推荐
- 💰 成本优化建议
- ⚡ 供货周期优化
- 🔄 交期保障方案

---

*注：此文章由系统自动生成，报价和具体解决方案为公司隐私信息，不在此公开。*`;

    const titleEn = `BOM Optimization Request - ${parsed.totalItems} Components Sourcing`;
    const contentEn = `## Anonymous BOM Optimization Request

A BOM list containing **${parsed.totalItems}** components has been submitted for optimization.

### Required Components (Partial)

| Part Number | Quantity |
|-------------|----------|
${sampleParts.map(p => `| ${p.partNumber} | ${p.quantity} |`).join('\n')}
${moreCount > 0 ? `| ... | ${moreCount} more items |` : ''}

### Optimization Focus

- 📊 Domestic alternative recommendations
- 💰 Cost optimization suggestions
- ⚡ Lead time optimization
- 🔄 Delivery guarantee solutions

---

*Note: This article is auto-generated by the system. Quotation details and specific solutions are confidential.*`;

    const keywords = ['BOM优化', '元器件替代', '成本控制', 'supply chain', 'component sourcing'];
    
    const { error } = await supabase
      .from('blogs')
      .insert({
        author_id: SYSTEM_USER_ID,
        title_cn: titleCn,
        title_en: titleEn,
        content_cn: contentCn,
        content_en: contentEn,
        keywords: keywords.join(', '),
        status: 'published',
        category: 'bom_optimization'
      });
    
    if (!error) {
      console.log('[BOM Auto Publish] ✅ BOM optimization article published successfully');
      return true;
    } else {
      console.error('[BOM Auto Publish] ❌ Failed to publish:', error);
      return false;
    }
  } catch (e) {
    console.error('[BOM Auto Publish] ❌ Exception:', e);
    return false;
  }
}

export const POST: APIRoute = async ({ request }) => {
  try {
    const formData = await request.formData();
    
    const email = formData.get('email') as string;
    const bomText = formData.get('bomText') as string;
    const file = formData.get('file') as File | null;

    if (!email) {
      return new Response(
        JSON.stringify({ error: 'Email is required' }),
        { status: 400, headers: { 'Content-Type': 'application/json' } }
      );
    }

    // Step 1: 使用智能分流引擎分配销售
    const assignedSales = routeIncomingBOM(email);
    console.log('[Sales Routing] ==========================================');
    console.log('[Sales Routing] Assigned salesperson:', assignedSales.name, '-', assignedSales.email);
    console.log('[Sales Routing] Region:', assignedSales.id.includes('cn') ? 'CN' : assignedSales.id.includes('eu') ? 'EU' : 'Global');

    const payload: {
      email: string;
      bomText?: string;
      file?: {
        name: string;
        type: string;
        size: number;
        buffer: string;
      };
      timestamp: string;
    } = {
      email,
      bomText: bomText || undefined,
      timestamp: new Date().toISOString()
    };

    let fileUrl: string | undefined;
    let cloudStorageError: string | undefined;

    // Step 2: 文件上传到 Supabase Storage（优雅降级）
    if (file && file.size > 0) {
      const arrayBuffer = await file.arrayBuffer();
      const buffer = Buffer.from(arrayBuffer);
      
      payload.file = {
        name: file.name,
        type: file.type,
        size: file.size,
        buffer: buffer.toString('base64')
      };

      // 尝试上传到云端存储
      if (ENABLE_CLOUD_STORAGE) {
        try {
          const fileName = `bom/${Date.now()}_${file.name}`;
          console.log('[Supabase Storage] Uploading file:', fileName);
          
          const { error: uploadError } = await supabase.storage
            .from('bom-files')
            .upload(fileName, buffer, {
              contentType: file.type,
              upsert: false
            });

          if (!uploadError) {
            const { data: urlData } = supabase.storage
              .from('bom-files')
              .getPublicUrl(fileName);
            fileUrl = urlData.publicUrl;
            console.log('[Supabase Storage] ✅ File uploaded successfully:', fileUrl);
          } else {
            cloudStorageError = uploadError.message;
            console.error('[Supabase Storage] ❌ File upload failed:', cloudStorageError);
          }
        } catch (storageError) {
          cloudStorageError = storageError instanceof Error ? storageError.message : 'Unknown storage error';
          console.error('[Supabase Storage] ❌ Exception:', cloudStorageError);
        }
      } else {
        console.log('[Supabase Storage] ⚠️ Cloud storage disabled, skipping upload');
      }
    }

    console.log('[BOM Submit] ==========================================');
    console.log('[BOM Submit] Received submission:', {
      email: payload.email,
      hasFile: !!payload.file,
      fileName: payload.file?.name,
      fileSize: payload.file?.size,
      hasBomText: !!payload.bomText,
      timestamp: payload.timestamp,
      fileUrl,
      cloudStorageError
    });

    const ADMIN_EMAIL = import.meta.env.ADMIN_EMAIL;
    const RESEND_API_KEY = import.meta.env.RESEND_API_KEY;
    const SERVER_CHAN_KEY = import.meta.env.SERVER_CHAN_KEY;

    // 打印环境变量配置状态（隐藏敏感信息）
    console.log('[BOM Submit] Environment Configuration:');
    console.log('[BOM Submit]   ADMIN_EMAIL configured:', !!ADMIN_EMAIL);
    console.log('[BOM Submit]   RESEND_API_KEY configured:', !!RESEND_API_KEY);
    console.log('[BOM Submit]   SERVER_CHAN_KEY configured:', !!SERVER_CHAN_KEY);
    console.log('[BOM Submit]   Supabase Storage enabled:', ENABLE_CLOUD_STORAGE);
    console.log('[BOM Submit]   Assigned Sales:', assignedSales.name);

    // Step 3: 动态发送邮件通知（包含智能分流信息）
    let emailSent = false;
    if (ADMIN_EMAIL && RESEND_API_KEY) {
      console.log('[Resend] Starting email sending...');
      
      const emailSubject = `新 BOM 询价 - ${email} | 分配给: ${assignedSales.name}`;
      const emailHtml = `
        <html>
          <body style="font-family: Arial, sans-serif; padding: 20px; background-color: #f4f4f4;">
            <div style="max-width: 600px; margin: 0 auto; background-color: white; padding: 30px; border-radius: 8px;">
              <h2 style="color: #333; margin-top: 0;">新 BOM 询价提交</h2>
              
              <!-- 智能分流信息 -->
              <div style="margin-bottom: 20px; padding: 15px; background-color: #fff3cd; border: 1px solid #ffeeba; border-radius: 4px;">
                <h3 style="color: #856404; margin-top: 0; font-size: 16px;">🔄 【系统智能分流】</h3>
                <p style="color: #856404; margin: 5px 0;">本单已自动分配给销售人员：<strong>${assignedSales.name}</strong></p>
                <p style="color: #856404; margin: 5px 0;">负责销售邮箱：${assignedSales.email}</p>
                <p style="color: #856404; margin: 5px 0; font-size: 12px;">后续成单将计入该员工业绩</p>
              </div>
              
              <p><strong>客户邮箱:</strong> ${email}</p>
              <p><strong>提交时间:</strong> ${new Date(payload.timestamp).toLocaleString('zh-CN')}</p>
              
              ${bomText ? `
                <div style="margin-top: 20px; padding: 15px; background-color: #f9f9f9; border-left: 4px solid #f39c12;">
                  <h3 style="color: #555; margin-top: 0;">BOM 内容:</h3>
                  <pre style="white-space: pre-wrap; word-wrap: break-word; color: #333; font-size: 13px;">${bomText}</pre>
                </div>
              ` : ''}
              
              ${payload.file ? `
                <div style="margin-top: 20px; padding: 15px; background-color: #f9f9f9; border-left: 4px solid #27ae60;">
                  <h3 style="color: #555; margin-top: 0;">附件信息:</h3>
                  <p><strong>文件名:</strong> ${payload.file.name}</p>
                  <p><strong>文件大小:</strong> ${(payload.file.size / 1024).toFixed(2)} KB</p>
                  <p><strong>文件类型:</strong> ${payload.file.type}</p>
                  ${fileUrl ? `<p><strong>下载链接:</strong> <a href="${fileUrl}" target="_blank">点击下载</a></p>` : ''}
                </div>
              ` : ''}
              
              <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; color: #888; font-size: 12px;">
                <p>此邮件由 PNDS BOM Hub 自动发送</p>
              </div>
            </div>
          </body>
        </html>
      `;

      const attachments: any[] = [];
      if (payload.file) {
        attachments.push({
          filename: payload.file.name,
          content: Buffer.from(payload.file.buffer, 'base64')
        });
      }

      try {
        const resendResponse = await fetch('https://api.resend.com/emails', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${RESEND_API_KEY}`
          },
          body: JSON.stringify({
            from: 'PNDS BOM Hub <onboarding@resend.dev>',
            to: ADMIN_EMAIL,
            subject: emailSubject,
            html: emailHtml,
            attachments: attachments.length > 0 ? attachments : undefined
          })
        });

        if (resendResponse.ok) {
          const responseData = await resendResponse.json();
          emailSent = true;
          console.log('[Resend] ✅ Email sent successfully! ID:', responseData.id);
        } else {
          const errorData = await resendResponse.json();
          console.error('[Resend] ❌ FAILED to send email:', errorData.message);
        }
      } catch (emailError) {
        console.error('[Resend] ❌ Exception:', emailError);
      }
    } else {
      console.warn('[Resend] ⚠️ Skipping email notification - configuration missing');
    }

    // Step 4: 动态发送微信通知（优先使用分配销售的 wechat_key，降级到全局 KEY）
    let wechatSent = false;
    const effectiveWechatKey = assignedSales.wechat_key && assignedSales.wechat_key !== 'SCTxxxxxxxxxxxxxx' 
      ? assignedSales.wechat_key 
      : SERVER_CHAN_KEY;

    if (effectiveWechatKey) {
      const notifyTitle = `新BOM分流提醒 | ${assignedSales.name}`;
      const despParts = [
        `负责销售: ${assignedSales.name}`,
        `客户: ${email}`,
        `提交时间: ${new Date(payload.timestamp).toLocaleString('zh-CN')}`
      ];
      if (bomText) despParts.push(`BOM内容: ${bomText.substring(0, 50)}${bomText.length > 50 ? '...' : ''}`);
      if (payload.file) despParts.push(`附件: ${payload.file.name}`);
      const notifyDesp = despParts.join('%0A');
      
      console.log('[ServerChan] Sending notification to:', assignedSales.name);
      
      try {
        const notifyResponse = await fetch(
          `https://sctapi.ftqq.com/${effectiveWechatKey}.send?title=${encodeURIComponent(notifyTitle)}&desp=${notifyDesp}`,
          { method: 'GET' }
        );
        
        if (notifyResponse.ok) {
          wechatSent = true;
          console.log('[ServerChan] ✅ WeChat notification sent successfully to:', assignedSales.name);
        } else {
          console.error('[ServerChan] ❌ Failed to send WeChat notification');
        }
      } catch (notifyError) {
        console.error('[ServerChan] ❌ Error:', notifyError);
      }
    } else {
      console.warn('[ServerChan] ⚠️ Not configured, skipping WeChat notification');
    }

    // Step 5: 保存到 Supabase 数据库（优雅降级）
    let dbSaved = false;
    if (ENABLE_CLOUD_STORAGE) {
      try {
        const savedSubmission = await saveBOMSubmission({
          customer_email: email,
          bom_text: bomText || undefined,
          file_url: fileUrl,
          assigned_sales_id: assignedSales.id,
          region: assignedSales.id.includes('cn') ? 'cn' : assignedSales.id.includes('eu') ? 'eu' : 'global'
        });
        dbSaved = true;
        console.log('[Supabase DB] ✅ BOM submission saved successfully:', savedSubmission.id);
      } catch (dbError) {
        console.error('[Supabase DB] ❌ Failed to save submission:', dbError);
        // 数据库失败不影响通知发送
      }
    } else {
      console.log('[Supabase DB] ⚠️ Cloud database disabled, skipping save');
    }

    // Step 5.5: 自动发布BOM优化板块文章（匿名）
    let autoPublished = false;
    if (bomText && bomText.trim()) {
      autoPublished = await autoPublishBOMOptimization(bomText);
    }

    console.log('[BOM Submit] ==========================================');
    console.log('[BOM Submit] Final Status:');
    console.log('[BOM Submit]   Email sent:', emailSent);
    console.log('[BOM Submit]   WeChat sent:', wechatSent);
    console.log('[BOM Submit]   DB saved:', dbSaved);
    console.log('[BOM Submit]   Auto published:', autoPublished);
    console.log('[BOM Submit]   File URL:', fileUrl || 'N/A');

    // Step 6: 重定向回原页面
    const redirectUrl = request.headers.get('referer') || '/bom-hub';
    const separator = redirectUrl.includes('?') ? '&' : '?';
    const status = emailSent || wechatSent ? 'success' : 'partial';
    
    return new Response(null, {
      status: 303,
      headers: {
        'Location': `${redirectUrl}${separator}status=${status}`
      }
    });

  } catch (error) {
    console.error('[BOM Submit] ❌ Unexpected error:', error);
    
    // 即使发生异常，也要尽力发送通知
    try {
      const ADMIN_EMAIL = import.meta.env.ADMIN_EMAIL;
      const RESEND_API_KEY = import.meta.env.RESEND_API_KEY;
      
      if (ADMIN_EMAIL && RESEND_API_KEY) {
        await fetch('https://api.resend.com/emails', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${RESEND_API_KEY}`
          },
          body: JSON.stringify({
            from: 'PNDS BOM Hub <onboarding@resend.dev>',
            to: ADMIN_EMAIL,
            subject: 'BOM提交异常通知',
            html: `<p>系统遇到异常：${error}</p>`
          })
        });
      }
    } catch (notifyError) {
      console.error('[BOM Submit] Failed to send error notification:', notifyError);
    }
    
    const redirectUrl = request.headers.get('referer') || '/bom-hub';
    const separator = redirectUrl.includes('?') ? '&' : '?';
    return new Response(null, {
      status: 303,
      headers: {
        'Location': `${redirectUrl}${separator}status=error`
      }
    });
  }
};